# Generated by Django 4.2.2 on 2023-06-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_userprofile_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cnf_password',
        ),
    ]
