# Generated by Django 4.2.2 on 2023-06-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_remove_userprofile_cnf_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
